2020-12-26 11:15:16,752 INFO: Microblog startup [in C:\Users\jebakuma\OneDrive - HP Inc\learning\flask\flask-mega-tutorial-miguel-grinberg\microblog_clean\application\__init__.py:66]
2020-12-26 11:28:27,545 INFO: Microblog startup [in C:\Users\jebakuma\OneDrive - HP Inc\learning\flask\flask-mega-tutorial-miguel-grinberg\microblog_clean\application\__init__.py:66]
2020-12-26 11:28:43,876 ERROR: Exception on /user/Susan [GET] [in c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\jebakuma\OneDrive - HP Inc\learning\flask\flask-mega-tutorial-miguel-grinberg\microblog_clean\application\routes.py", line 79, in user
    posts = user.posts.oder_by(Post.timestamp.desc()).paginate(
AttributeError: 'AppenderBaseQuery' object has no attribute 'oder_by'
2020-12-26 11:29:04,279 INFO: Microblog startup [in C:\Users\jebakuma\OneDrive - HP Inc\learning\flask\flask-mega-tutorial-miguel-grinberg\microblog_clean\application\__init__.py:66]
2020-12-26 11:29:09,451 ERROR: Exception on /user/Susan [GET] [in c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\jebakuma\OneDrive - HP Inc\learning\flask\flask-mega-tutorial-miguel-grinberg\microblog_clean\application\routes.py", line 91, in user
    return render_template('user.html', user=user, posts=posts, form=form,
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\jebakuma\OneDrive - HP Inc\learning\flask\flask-mega-tutorial-miguel-grinberg\microblog_clean\application\templates\user.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Users\jebakuma\OneDrive - HP Inc\learning\flask\flask-mega-tutorial-miguel-grinberg\microblog_clean\application\templates\base.html", line 39, in top-level template code
    {% block app_content %}
  File "C:\Users\jebakuma\OneDrive - HP Inc\learning\flask\flask-mega-tutorial-miguel-grinberg\microblog_clean\application\templates\user.html", line 49, in block "app_content"
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2020-12-26 11:29:27,543 INFO: Microblog startup [in C:\Users\jebakuma\OneDrive - HP Inc\learning\flask\flask-mega-tutorial-miguel-grinberg\microblog_clean\application\__init__.py:66]
2020-12-26 11:31:01,361 INFO: Microblog startup [in C:\Users\jebakuma\OneDrive - HP Inc\learning\flask\flask-mega-tutorial-miguel-grinberg\microblog_clean\application\__init__.py:66]
2020-12-26 11:32:29,748 INFO: Microblog startup [in C:\Users\jebakuma\OneDrive - HP Inc\learning\flask\flask-mega-tutorial-miguel-grinberg\microblog_clean\application\__init__.py:66]
2020-12-26 11:36:45,170 INFO: Microblog startup [in C:\Users\jebakuma\OneDrive - HP Inc\learning\flask\flask-mega-tutorial-miguel-grinberg\microblog_clean\application\__init__.py:66]
